from .region_service import RegionService
from .department_service import DepartmentService
from .epci_service import EPCIService
from .city_service import CityService
from .address_service import AddressService
from .building_service import BuildingService
from .parcel_service import ParcelService
from .housing_service import HousingService
from .data_integration_service import DataIntegrationService
from .geocodage_service import GeocodageService
from .reference_geographical_database_service import ReferenceGeographicalDatabaseService
