version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    command: bash -c " sleep 10 && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    image: rpls-back
    volumes:
      - .:/rpls-back
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgis/postgis:latest
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
